# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'scratch'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['nodeexporter:9100']
