version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  monitor-net:
    driver: bridge

services:
  nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    privileged: true
    image: prom/prometheus
    user: "${UID}:${GID}"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prom-config.yaml'
      - '--storage.tsdb.path=/prometheus'
    links:
      - nodeexporter
    networks:
      - monitor-net
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    privileged: true
    user: "${UID}:${GID}"
    depends_on:
      - prometheus
    links:
      - prometheus
    networks:
      - monitor-net
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    # env_file:
    #   - ./grafana/config.monitoring
    restart: always

